#
# This source file is part of the Stanford Biodesign Digital Health MyHeart Counts open-source project
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Deployment

on:
  push:
    branches:
      - main
    tags:
      - 'region-*'
  workflow_dispatch:
    inputs:
      environment:
        description: |
          The GitHub deployment environment
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production-uk
          - production-us
  workflow_call:
    inputs:
      environment:
        description: |
          The GitHub deployment environment
        required: false
        type: string
        default: development

concurrency:
  group: deployment
  cancel-in-progress: false

jobs:
  determineenvironment:
    name: Determine Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      region: ${{ steps.set-region.outputs.region }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Determine Environment
        id: set-env
        run: |
          if [[ -z "${{ inputs.environment }}" ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
          else
            echo "environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          fi
      - name: Extract Region from Tag
        id: set-region
        run: |
          if [[ "${{ github.ref }}" == refs/tags/region-* ]]; then
            REGION="${{ github.ref_name }}"
            REGION="${REGION#region-}"
            echo "region=$REGION" >> $GITHUB_OUTPUT
          else
            echo "region=" >> $GITHUB_OUTPUT
          fi

  vars:
    name: Inject Environment Variables In Deployment Workflow
    needs: determineenvironment
    runs-on: ubuntu-latest
    environment: ${{ needs.determineenvironment.outputs.environment }}
    outputs:
      FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
    steps:
      - run: |
          echo "Injecting Environment Variables In Deployment Workflow: ${{ vars.FIREBASE_PROJECT_ID }}"

  buildandtest:
    name: Build and Test
    needs: determineenvironment
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      contents: read
      checks: write
    secrets: inherit

  deployfirebase:
    name: "Deploy to ${{ needs.determineenvironment.outputs.environment }}"
    needs: [buildandtest, determineenvironment, vars]
    # Check if this is a push to main without region tag (run then the full deployment sequence) -
    # OR if this is a workflow_dispatch or workflow_call with specific environment
    # OR if this is a tag with region specified 
    if: |
      (github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')) ||
      (needs.determineenvironment.outputs.environment != '') ||
      (needs.determineenvironment.outputs.region != '')
    uses: StanfordBDHG/.github/.github/workflows/firebase-deploy.yml@v2
    permissions:
      contents: read
    with:
      customcommand: "npm run install"
      environment: ${{ needs.determineenvironment.outputs.region != '' && format('production-{0}', needs.determineenvironment.outputs.region) || needs.determineenvironment.outputs.environment }}
      arguments: '--project ${{ needs.vars.outputs.FIREBASE_PROJECT_ID }}'
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}